name: Build and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Sets up the Node environment
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # 'ci' is faster and more reliable than 'install' for CI environments

      - name: Run Lint
        run: npm run lint

      - name: Run Build
        run: npm run build
